### ISSUE TITLE
API roadmap

### ISSUE THREAD

**Issue by alex-r-bigelow** [hdc-arizona/traveler-integrated#76]
My imagined roadmap toward a `pip3 install`-able traveler library (critique / edits / ideas welcome!):

### Reviewing the [new API code](https://github.com/hdc-arizona/traveler-integrated/tree/ui-overhaul/api)
- [ ] In addition to skimming the code, it might be worth exploring it via `git checkout ui-overhaul && ./serve.py` and navigating to [the Swagger interface](http://localhost:8000/docs)) \*
- [ ] Record any thoughts / critique about the structure... are things confusing? Is this properly RESTful? (To what extent do we need to be?)
- [ ] Imagine that you're querying these endpoints from a Jupyter notebook to make custom tables / charts. What kinds of queries might be missing?

\* <sub>Note that most views are still broken if you open the Web interface—but the Tags + Folders for organizing datasets should at least be working!</sub>

### Plan a python wrapper for the API
- [ ] This is a pretty common practice; might be worth skimming [this tutorial](https://semaphoreci.com/community/tutorials/building-and-testing-an-api-wrapper-in-python)
- [ ] For traveler-specific examples of communicating with the API from python, there are some examples in JetLag for [individual files](https://github.com/STEllAR-GROUP/JetLag/blob/703e192210024bc4d4e3cfcad50f6c8ae245dc66/visualizeInTraveler.py#L65) as well as [streaming an OTF2 trace](https://github.com/STEllAR-GROUP/JetLag/blob/703e192210024bc4d4e3cfcad50f6c8ae245dc66/visualizeInTraveler.py#L79)
- [ ] Open question: how should we deal with the case where someone tries to `import traveler`, but it currently isn't running? What would the pros and cons\*\* be for auto-starting the server if that happens?
- [ ] If we rewrote `bundle.py` to use our new python wrapper for the API (instead of directly importing `data_store`), that would make it possible to upload multiple runs at once. Would we need to change anything about the API to make this possible?

\*\* <sup>**Pro:** this could simplify setup for both Rod's analysis use case, as well as simplify Steve's JetLag setup... but **Con:** auto-starting from an `import` statement wouldn't allow for any configuration like the port that traveler should use, or what directory we should use for storing things like pickles. Is there a better way to do this?</sup>

### Bonus things to think about:
- [ ] An API wrapper like this would give us a good way to start thinking about automated regression testing, at least in terms of data bundling + querying. Are there frameworks that we should use? What kinds of tests should we run?
- [ ] The ongoing refactor is making traveler's individual views modular enough that it should be possible to embed them directly in Jupyter's cells\*\*\*. In a round-trip use case, how could / should an embedded view work with our python API wrapper? I'm imagining something like `traveler.getPrimitiveDetails(embeddedTreeView.selectedPrimitiveId)`

\*\*\* <sup>The new versions of `uki.js` make it so that we'd only need to strip them of their GoldenLayout mixins, and probably add a mixin to help them fit better in Jupyter's DOM instead—B2 and/or mage probably have cool ways of doing this</sup>
